### PR TITLE
fix finalizeAndSubmitTx waterfall

### LINKED ISSUE #343: Callback is undefined in signTransaction function
Looks like signTransaction is not correctly calling inside finalizeAndSubmitTx waterfall. I'm trying to implement signTransaction, but cb argument is not defined.

Code:
```
engine.addProvider(new HookedWalletSubprovider({
    signTransaction: async function (txParams, cb) {
      cb(null, client.signTransaction(txParams));
    }
});
```
Error:
```
instrument.ts:129 TypeError: cb is not a function
    at HookedWalletSubprovider.signTransaction
```

### PR DESCRIPTION
**Pull request by MicrowaveDev**
Closes #343

### CODE REVIEW

**Comment by sterlu** [comment]
Would love to see this merged in. Seems super quick to check and approve @rekmarks 🤞

**Comment by rekmarks** [comment]
@Jonybang do you mind fixing the `waterfall` in `finalizeTx` too? https://github.com/MetaMask/web3-provider-engine/blob/d611db5950cd3433470f08d5c4b80f42a6199f49/subproviders/hooked-wallet.js#L587-L590

**Review by Gudahtt — COMMENTED** [review]
I don't follow why the previous implementation didn't work :thinking:  This looks equivalent to me.

**Comment by mcmire** [comment]
Thank you for this pull request, but we are actively phasing out this package in favor of `json-rpc-engine` and its related packages, so I am going to close this. In this particular case, HookedWalletSubprovider in this package has been superceded by [`createWalletMiddleware` in `eth-json-rpc-middleware`](https://github.com/MetaMask/eth-json-rpc-middleware/blob/254a66cf5f067f35db96c6a5740c8da9a79e495d/src/wallet.ts). While we still intercept `eth_sendTransaction`, we no longer provide a default implementation for `processTransaction`, instead expecting the client to always provide that logic. If there is any missing functionality from that middleware, please submit a pull request there.

**Pull request closed without merging**
