### PR TITLE
Remove vulnerable version of cross-fetch

### LINKED ISSUE #401: `cross-fetch` can be removed from the dependece list
`cross-fetch` was replaced by `eth-json-rpc-middleware/fetch` at the commit https://github.com/MetaMask/web3-provider-engine/commit/eeefd6f4c5363713c5f0c9a207bd7e98e7e26f9b , the older version of cross-fetch has a vulnerability and package managers will be complaining about it. It can be removed without problems.

### PR DESCRIPTION
**Pull request by wbt**
Closes #401.

### CODE REVIEW

**Comment by brianlenz** [comment]
Any chance we can get this merged and get a `16.0.4` release pushed?

**Comment by brianlenz** [comment]
@wbt, you probably should run a `yarn install` with the change to get `yarn.lock` updated, too. But having said that, I realized this alone won't solve the root of the issue, as it's also a transitive dependency from `eth-json-rpc-infura` 🙈 

https://github.com/MetaMask/web3-provider-engine/blob/main/yarn.lock#L3338

**Comment by wbt** [comment]
@brianlenz I've [learned the hard way](https://github.com/ChainSafe/web3.js/pull/4861#discussion_r831017580) to exclude package-lock files from PRs to web3 projects. If a maintainer wants to do that, or if someone else wants to issue a PR against my branch awaiting a maintainer's indication that that can be merged first, fine, but I'm not going to sink my own PR by violating a rule like that.

**Review by mcmire — APPROVED** [review]
Okay, I took a look and you're right, it seems like this dependency is no longer used. Seems like someone else in #400 had the same idea too. Thanks so much and sorry for the long delay on this.

**Comment by jeffwalsh** [comment]
is this available in a public version? i don't see a 16.0.4 with this change  a @brianlenz was asking for above

**Comment by wbt** [comment]
No, there has not been a publish since the time this PR was merged.

**Comment by mcmire** [comment]
16.0.4 is now released with this change. Cheers!

**Pull request merged**
